export const GET_WEATHER = "GET_WEATHER";
export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const WEATHER_LOADING = "WEATHER_LOADING";
export const WEATHER_LOADED = "WEATHER_LOADED";
export const WEATHER_ERROR = "WEATH_ERROR";
export const CHANGE_UNIT = "CHANGE_UNIT";
